/**
 * unknown-keys.ts — auto-generated by deploy-content-to-github
 *
 * Keys that exist in the content database but could not be deployed directly
 * into source files (e.g. keys used in dynamic contexts, meta tags, or
 * server-side rendered paths that the source scanner cannot reach).
 *
 * The content system checks this map as a fallback AFTER the database and
 * BEFORE the hardcoded fallback prop, so values here are always live.
 *
 * DO NOT edit this file manually — it is overwritten on every deploy.
 * Last updated: 2026-06-25T13:38:35.564Z
 */

export const unknownKeysMap: Record<string, string> = {
  "simple-payment-now-description": "Betal nu med kort, Apple Pay eller Klarna.",
  "simple-payment-invoice-title": "Faktura",
  "simple-payment-onsite-title": "Betal ved optagelsen",
  "simple-payment-onsite-description": "Betal kort eller kontant ved optagelsen.",
  "simple-payment-invoice-description": "Betal efter levering.",
  "simple-payment-now-title": "Betal nu",
};
