/**
 * unknown-keys.ts — auto-generated by deploy-content-to-github
 *
 * Keys that exist in the content database but could not be deployed directly
 * into source files (e.g. keys used in dynamic contexts, meta tags, or
 * server-side rendered paths that the source scanner cannot reach).
 *
 * The content system checks this map as a fallback AFTER the database and
 * BEFORE the hardcoded fallback prop, so values here are always live.
 *
 * DO NOT edit this file manually — it is overwritten on every deploy.
 * Last updated: 2026-07-01T19:07:05.706Z
 */

export const unknownKeysMap: Record<string, string> = {
  "simple-payment-now-description": "Betal nu med kort, Apple Pay eller Klarna.",
  "simple-payment-invoice-title": "Faktura",
  "simple-payment-onsite-title": "Betal ved optagelsen",
  "simple-payment-onsite-description": "Betal kort eller kontant ved optagelsen.",
  "simple-payment-invoice-description": "Betal efter levering.",
  "simple-payment-now-title": "Betal nu",
  "testimonials-review-1": "[\n  {\n    \"user\": {\n      \"name\": \"Kim Lan Harris\",\n      \"thumbnail\": \"https://lh3.googleusercontent.com/a-/ALV-UjWyOEm67fLbfBdz92XJl3d4CEMRAxOelUy1FOKjo51vQYjfH2s_=w144-h144-p-rp-mo-br100\"\n    },\n    \"rating\": 5,\n    \"snippet\": \"Vi har i vikiallo fået Felix Berg til at lave drone video af vores bygninger. Vi er meget tilfredse med hele forløbet, fra han tog kontakt og til det færdige resultat.\",\n    \"link\": \"https://www.google.com/maps/contrib/111371785121815970915/place/ChIJq5JklwgFuQ0RREPIKUg0EHs/@55.5033574,9.4834173,14z/data=!4m6!1m5!8m4!1e1!2s111371785121815970915!3m1!1e1?hl=da-DK&entry=ttu&g_ep=EgoyMDI2MDYyMi4wIKXMDSoASAFQAw%3D%3D\",\n    \"business\": \"Vikiallo ApS\"\n  },\n  {\n    \"user\": {\n      \"name\": \"Marie Nygaard\",\n      \"thumbnail\": \"https://lh3.googleusercontent.com/a/ACg8ocKLM-DpprnkxtCZF0TmV_h2AmVz0p1mUvJcl16bZXU2wNHu8w=s120-c-rp-mo-br100\"\n    },\n    \"rating\": 5,\n    \"snippet\": \"Vi var lidt sent ude med at skulle bruge billeder til en gave, men FLAI var super behjælpelige og fleksible, så vi nåede det. Vi har fået leveret et stort udvalg af billeder i god kvalitet og flotte farver. Vi vil helt sikkert benytte os af FLAI igen en anden gang.\",\n    \"link\": \"https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT2tKRFpsTlJRbmxvTjB4blZEbGhNR2RHVGxKTE9HYxAB!2m1!1s0x0:0x7b10344829c84344!3m1!1s2@1:CAIQACodChtycF9oOkJDZlNRQnloN0xnVDlhMGdGTlJLOGc%7C%7C?hl=en-US\"\n  }\n]",
  " testimonials-google-rating": "{ \"rating\": 5, \"reviewCount\": 2, \"link\": \"https://www.google.com/maps/place/Flai+-+Dronefoto+of+video/@55.5186897,9.4869416,17z/data=!4m18!1m9!3m8!1s0xdb90508976492ab:0x7b10344829c84344!2sFlai+-+Dronefoto+of+video!8m2!3d55.5186897!4d9.4869416!9m1!1b1!16s%2Fg%2F11yv8d__m8!3m7!1s0xdb90508976492ab:0x7b10344829c84344!8m2!3d55.5186897!4d9.4869416!9m1!1b1!16s%2Fg%2F11yv8d__m8?entry=ttu&g_ep=EgoyMDI2MDYyOC4wIKXMDSoASAFQAw%3D%3D\" }",
};
